sudo: false
language: rust
rust:
- stable
before_script:
- rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
- rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu
script:
- cargo fmt -- --check
- cargo clippy --all
- cargo build
- cargo test --all
cache: cargo